name: Labeling new pull request with respective FOSS Program
on:
  pull_request_target:
    branches:
      - master
    types:
      - opened

jobs:
  add-label:
    name: Add GSSOC21 Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: christianvuerings/add-labels@v1
        with:
          labels: |
            gssoc21
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
